### ISSUE TITLE
Add "weeks" as accuracy

### ISSUE THREAD

**Issue by milanoleonardo** [idmc-labs/idmc-database-feedback#10]
Add “weeks” as accuracy. This would be useful for something like “As a government military offensive to retake Mosul from the Islamic State in Iraq and the Levant (ISIL) continues to gather momentum, at least 150,000 more people have already  ed Shirqat and Al Qayyarah, located near Mosul, in recent weeks”

**Comment by allochi** [comment]
Up for voting?
