### ISSUE TITLE
Test DB Issues (27 Oct 2017)

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#122]
Issues when Testing IDMC database
27 Oct 2017

-  Currently “home” is the documents list… why? There’s no “home” menu button/link
- System hangs when saving after adding publisher
- Edit Document: when adding a quick fact, it would be great that it automatically includes the same country and displacement type as document.  
- Editing sub-fact: under Data, it would be good to move the Term field just after the figure to put context to the number. Also can Household Size only be visible when selecting the Unit “household”? It doesn’t make sense from a usability stand point to see the household size when the unit is “person”
- Under Edit Sub Fact: Why is there a tab “Facts”?
- Under Edit Sub Fact: The Association section is blank even though a fact is associated to an event
- Under Countries: There are no documents listed
- For fact class, what is a Fact vs. Sub Fact and why does it matter?
- Choosing Hazard Type: currently set as case sensitive (ex. I can find “Cyclone” but when I type “cyclone”, nothing is found). Also strange that I “Tornado” doesn’t show up when I type it into field.
- Sources & Publishers: Type list needs to be cleaned up
- Documents: What is the purpose of the buttons “All/Any” in the search beside Sources, Publishers, and Countries?

**Comment by allochi** [comment]
Hi, Please consider posting each issue in its own post in the future. I'm reposting this issue with a numbered list to use as a reference in my replies

1. Currently “home” is the documents list… why? There’s no “home” menu button/link
2. System hangs when saving after adding publisher
3. Edit Document: when adding a quick fact, it would be great that it automatically includes the same country and displacement type as document.
4. Editing sub-fact: under Data, it would be good to move the Term field just after the figure to put context to the number. Also can Household Size only be visible when selecting the Unit “household”? It doesn’t make sense from a usability stand point to see the household size when the unit is “person”
5. Under Edit Sub Fact: Why is there a tab “Facts”?
6. Under Edit Sub Fact: The Association section is blank even though a fact is associated to an event
7. Under Countries: There are no documents listed
8. For fact class, what is a Fact vs. Sub Fact and why does it matter?
9. Choosing Hazard Type: currently set as case sensitive (ex. I can find “Cyclone” but when I type “cyclone”, nothing is found). Also strange that I “Tornado” doesn’t show up when I type it into field.
10. Sources & Publishers: Type list needs to be cleaned up
11. Documents: What is the purpose of the buttons “All/Any” in the search beside Sources, Publishers, and Countries?

**Comment by ghost** [comment]
No problem Ali. Will log each one as a separate issue next time.

**Comment by allochi** [comment]
1. **Closed:** A user home page has been added (empty for now - will include user dashboard later)
2. **Pending:** I couldn't replicate the error.
3. **Not applicable:** The countries field is a multiple values field, the fact field is a single dropdown value field. (Maybe filter the dropdown to show only countries from the document field, if so please open a new issue and mark it with a `Proposal: subject...`)
4. Two requests in one:
a. **Done:** Good idea, I have move the field - It will show up next update
b. **Done:** Good idea, I have implemented the functionality - It will show up next update  
5. **Closed:** I tried to fix this by removing the tab, but it didn't work well, for now, facts and subfacts will have this tab disabled.
6. **Fixed:** The "events" component has been revisited and fixed
7. **Fixed** The table was reading the wrong source of data
8. What do you mean?
9. **Closed:** The cascade component doesn't allow for case insensitive search, I posted a request to the library providers to support this feature.
10. **WIP:** Part of the data cleanup and migration.
11. If you select all, then all the tags must be included/selected, any mean any of the tags, so All ("A","B") will show only those record that contain both, Any("A","B") records that either contain A or B or both.

Fixes will be pushed with the next backend update - v2.0-beta.2

Please post any remaining request individually, thanks!
