### ISSUE TITLE
Separating Sudan and South Sudan in the fact search

### ISSUE THREAD

**Issue by raphaellamontandon** [idmc-labs/idmc-database-feedback#128]
This is definitely not a priority, but is becoming more noticeable as we add more and more facts in the DB for the data blitz. 

There is no 'not' search button, so when we search for a country like 'Sudan' in the fact search it gives us all of the results for South Sudan as well, which is confusing.

Voila! Putting it out there.

**Comment by allochi** [comment]
There is a country dropdown in the new system, the user can list the desired list of countries.
