### ISSUE TITLE
Pdf uploads: Documents fail to upload?

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#130]
- When I tried to create a document from a pdf file today, I could not seem to see whether the document actually uploaded or not.
- I'm unsure about whether this is because the document failed to upload or whether it is because there is no link to the uploaded document included on the document page, but it would be great to look into this.
Thanks, Marta.

**Comment by allochi** [comment]
Fixed
expected update @v2.0-beta.4
