### ISSUE TITLE
Multiple error messages when opening "new contact" tab

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#133]
- When I clicked on "new contact" to try to to add a new contact to the database, 7 error messages appeared at once. They have disappeared now and did not have the time to not the exact message in the error messages, but I thought that it might be good to know.

**Comment by andreslizcano** [comment]
And after they are gone, new error messages keep showing up when I type things in the fields. It isn't possible to save the new contact.

**Comment by allochi** [comment]
This is fixed.
expected update v2.0-beta.4
