### ISSUE TITLE
Under "source types": Each source type is included multiple types

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#136]
When you want to add a source or publisher to the database and you are about to enter it to the database, each source type is included in the roll down several times (e.g. it says "Red Cross/Red Crescent Movement" 4 times, "other international/supranational organisations" four times, and "media" multiple times with different spellings, etc).

**Comment by allochi** [comment]
Publishers table in the database need to be cleaned up

**Comment by allochi** [comment]
The publisher type has been cleaned up a little, although I think this require more work.
