### ISSUE TITLE
No breadcrumb when creating a new item 

### ISSUE THREAD

**Issue by raphaellamontandon** [idmc-labs/idmc-database-feedback#162]
When creating new items (ex contextual analysis, significant updates), there is no breadcrumb--- this is a problem as you can forget where you are in the db. It is sort of floating, would be good to have on the page a breadcrumb which shows you where in the db you are.

**Comment by allochi** [comment]
Country name has been added to the title as a hyperlink.

expected update v2.0-beta.4
