### ISSUE TITLE
Suggestion: preview for contextual analysis, challenges etc.

### ISSUE THREAD

**Issue by raphaellamontandon** [idmc-labs/idmc-database-feedback#164]
It might be useful for the contextual analysis, updates etc to have a preview of what is written. This will save us having to click on the items individually, and we can have an idea at a glance.

**Comment by andreslizcano** [comment]
I'm not sure about the reason for making several entries to contextual analysis, besides having the possibility to add updates. Why not having one Contextual analysis section that is edited whenever necessary?

**Comment by raphaellamontandon** [comment]
Hmm...I don't understand what you mean Andrés. Do you mean that you think the updates and contextual analysis section should be one and the same? I would agree with that actually. 

What I was referring to would be, instead of having a link, to have a comments box that is immediately visible, so that people can see the content update or contextual analysis (whatever it is) immediately when they go on the page.

**Comment by allochi** [comment]
@raphaellamontandon the content of the "Contextual Analysis", "Monitoring Challenges" and "Significant Updates" can be accessed in the table (row expand and show content)

expected update v2.0-beta.4
