### ISSUE TITLE
IDEA: Login page

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#168]
It would be great if hitting "return" on the keyboard could trigger the login... at the moment you have to click on the button.
![screen shot 2017-11-20 at 10 39 59 am](https://user-images.githubusercontent.com/1164551/33035455-f56a647c-cddf-11e7-8215-b8e3eba2c870.png)

**Comment by allochi** [comment]
fixed. expected update v2.0-beta.4
