### ISSUE TITLE
IDEA: Menu bar - Monitoring

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#169]
It would be great to be able to right click on the menu items under Monitoring so that "Open in a new tab" is possible. At the moment, you have to click on each item to go to it and cannot have multiple tabs/screens unless you open a window and then go through the link to the DB first.
![screen shot 2017-11-20 at 10 43 59 am](https://user-images.githubusercontent.com/1164551/33035430-e48c0124-cddf-11e7-8442-120746056e72.png)

**Comment by allochi** [comment]
In Chrome, you can duplicate the tab, the menu uses a javascript router, right click and ctrl+click won't work.
