### ISSUE TITLE
Contacts: Communication - no breadcrumb

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#171]
![screen shot 2017-11-20 at 10 55 26 am](https://user-images.githubusercontent.com/1164551/33035853-6f42124e-cde1-11e7-9e62-46c8a9c0f753.png)
there is no way to return to contact profile page after adding a communication item

**Comment by allochi** [comment]
The form now returns to the contact page once it has successfully saved.
