### ISSUE TITLE
Documents: Can't preview saved grab file

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#175]
![screen shot 2017-11-20 at 11 08 41 am](https://user-images.githubusercontent.com/1164551/33036443-3b84e092-cde3-11e7-9376-96d195fb5b07.png)

**Comment by allochi** [comment]
Extra testing required from my side.

**Comment by allochi** [comment]
Fixed in the next update
expected update v2.0-beta.4
