### ISSUE TITLE
Add Fact: Getting error when saving

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#176]
I get an error when trying to save a fact. I intentionally typed "d" in the year field and figured this what the error was... however, when I changed the year to "2017", I still received and error when saving. 
![screen shot 2017-11-20 at 11 11 35 am](https://user-images.githubusercontent.com/1164551/33036641-df7df65c-cde3-11e7-8e15-21bfe7015c91.png)

**Comment by allochi** [comment]
The form had a problem with `locations` field, it was change to be an array in the database, but not in the form, this has been fixed.

expected update v2.0-beta.4
