### ISSUE TITLE
Documents/Publishers: Existing sources not recognised when filling in document form

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#181]
- When trying to enter a new document in the database and filling in the "source" field, the database failed to recognise when typing sources that have been added to the source/contact repository
- E.g. I tried to type "UN" but this did not come up as one of the sources in the source repository, so I had to go to the source tab and search for "UN" - I could then see that the source had been added to the source repository, yet it did not appear in the drop down menu when entering it as a source for the document I was creating

**Comment by allochi** [comment]
This has been fixed by reducing the search threshold and order options by publisher name. 

expected update v2.0-beta.4
