### ISSUE TITLE
Dates (general): Always necessary to enter a date range when searching for a document, communications, fact, etc?

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#182]
- Not a huge priority but when searching based on dates, you have to enter a date range - would it be possible to search just based on one date as well? E.g. if you know which date a communication took place (identifying a date range takes some extra time and may not always be necessary).

**Comment by allochi** [comment]
Date search range was requested. The UI library doesn't provide a way to switch field type, but it does allow double click a date to fill-in both start & end dates with the same value. a tool hint has been added to guid the user. expected in  v2.0-beta.4
