### ISSUE TITLE
Facts are empty

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#186]
The facts tab/search is empty. When I try to search, nothing shows up. This happened at 1am GVA time on 25/11/2017

![screen shot 2017-11-24 at 3 56 25 pm](https://user-images.githubusercontent.com/1164551/33225634-258e76e0-d130-11e7-9179-c82044965e6c.png)

**Comment by allochi** [comment]
Hi Vincent, I'm sorry I didn't reply to this issue earlier. I'm closing this issue since we are moving to the new system soon.
