### ISSUE TITLE
Document: Failing to upload pdf by grabbing the URL

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#191]
When creating a new document, I had issues uploading this file https://reliefweb.int/sites/reliefweb.int/files/resources/WHDT2017_Final_Singles.pdf as the database wouldn't allow me to grab the URL (I had to upload it as a pdf). That works as well, of course, but good to know whether we could still upload pdfs by grabbing the url. 

Note: if that is relevant, I first indicated document type as "pdf" and not "web", but changed to "web" before trying to grab the file - could this be why it didn't work?

**Comment by allochi** [comment]
In the new release I tested both, and they both work, file upload and URL snapshots. I would recommend trying the same again with the new release, if the problem remains, please reopen the issue.

The type of the document doesn't affected the file attachment process, to be quite honest, I leaning toward removing it from the document serial number too.
