### ISSUE TITLE
Quick facts: Not possible to search for the country in the drop down menu

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#192]
When you create a new fact from a document, and you are indicating the country for which the quick fact is intended, it is not possible to search for the country in the drop down menu (you have to scroll down until you find the country). Used case; in the long run, it would save time not to have to scroll down until you find the country you're looking for. 

(Alternative) idea: what could be really smart is also if the countries that you can chose between when you indicate the country that the fact is valid for was based on the countries that are tagged in the document - in that case, the fact would in most cases be automatically associated to the country in question (when the document only concerns one country), and in other cases, the number of countries to choose from would be significantly reduced (saving time).

**Comment by MartaLindstrom** [comment]
PS. The same also goes for when you add a new communication.

**Comment by allochi** [comment]
Thanks for your feedback, these have been fixed. 

Your alternative idea seems nice, I can see some cases where it won't work, but you can always post it as a proposal, if everybody agrees we can implement it.
