### ISSUE TITLE
Quick facts: No indication of whether quick facts have been saved or not

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#193]
- When I tried to enter three quick facts from the same document, and clicked on "save all quick facts" there was no indication of whether the facts had actually saved or not - would it be possible to receive a message saying "Quick facts saved" or something like that? Just so that you know that the facts you entered had been saved?

**Comment by allochi** [comment]
There is one now, thanks for your feedback.
