### ISSUE TITLE
Country Profile: Having clicked on "significant update" and then clicked on "go back", the database doesn't remember which country profile you were working on

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#194]
- First, I searched for "Myanmar" among the country profiles, this worked great
- Second, I clicked on "new significant update" to see what that page looked like
- As I didn't enter a significant update however (let's say that I regretted this, or wanted to enter the update later), I clicked on "go back" - however, having done that, the page automatically reverted to the Afghanistan country page (which is first in the list). Would it be possible to make sure that the country pages remembers which country page you were working on? So that you don't have to scroll up and enter the country name each time you have worked on a significant update or other features?

**Comment by MartaLindstrom** [comment]
PS. The same also goes for when you click on "new contextual analysis", and then try to go back, However, when you save the contextual analysis or significant update, the database appears to remember which country page you were working on (you automatically return to the correct country webpage). It just doesn't seem to work when you regret the decision to open a new significant update or a new contextual analysis.

**Comment by allochi** [comment]
Breadcrumb added, this will provide structured navigation.
