### ISSUE TITLE
Issue: The fact is not linked to its document after I save it

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#197]
I noticed a bug in my latest facts: 

After I create a fact from a document, and save it, the corresponding document disappears.

On the opposite, if I open the document, the fact is listed under its "Fact" tab as expected.

See screenshot here

![screenshot 81](https://user-images.githubusercontent.com/23187213/34415691-5f3c045e-ebf0-11e7-8a8f-fea96b44b166.png)

**Comment by allochi** [comment]
Fixed.
