### ISSUE TITLE
Issue: Dates change after I save them

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#198]
The start & end dates of facts (New Displacement flow) change on their own after I save the fact.

Fore example: start date 16-12-2017 end date 19-12-2017 became 15-12-2017 and 18-12-2017; in other cases, they became 12-12-2017 and 15-12-2017, always after I saved the fact and even when I corrected them, they keep changing. It's weird.

![screenshot 80](https://user-images.githubusercontent.com/23187213/34415845-0fd40640-ebf1-11e7-9c63-49598877105f.png)

See screenshot here

**Comment by allochi** [comment]
Thanks, this has been fixed.
