### ISSUE TITLE
Issue (associated with #197): Can't check the document in already created Facts

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#199]
It appears that the issue with the document also happens with Facts previously created by others: I can't check the document the Fact is based upon because there is no link between the document and the Fact. When I click on the document blue icon, it opens a blank new document page instead of the document.

![screenshot 82](https://user-images.githubusercontent.com/23187213/34478759-fb4ff8a4-efa2-11e7-8877-26609ba20795.png)

**Comment by allochi** [comment]
Thanks a lot Luisa! This should be fix in the next update today.
