### ISSUE TITLE
Proposal: Saving search formula so that you don't have to re-enter the search terms multiple times

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#206]
What I did: Entered a search formula in the events section --> opened one of the search results --> went back to the search section through the breadcrumbs, with the intention of looking at the other search results that appeared --> noticed that the search results had disappeared, with the search fields being blank again. 

In general, would it be possible to save your searches so that you can go back to the results page, in case you don't open the right event/fact/document at the first attempt?

**Comment by allochi** [comment]
Fixed @2.03
