### ISSUE TITLE
Bug: Cannot link newly created facts to masterfacts 

### ISSUE THREAD

**Issue by raphaellamontandon** [idmc-labs/idmc-database-feedback#207]
If I try to link a fact to a masterfact, and then click update, this does not appear to save properly. 

![image](https://user-images.githubusercontent.com/33548793/34559234-6485b51c-f141-11e7-9c4d-df526f7715de.png)

**Comment by allochi** [comment]
Couldn't replicate the issue

**Comment by allochi** [comment]
Can you try again
