### ISSUE TITLE
IDMC Backend - V2.01 production: Selecting hazard type 

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#233]
To choose hazard type, it would be great to be able to type in the hazard (ex. earthquake) and be able to select this type from the bubble that opens... at the moment, once I select the type from the bubble, the bubble closes and then i have to click again the form field which then shows the bubble again with the hierarchy of hazards... then I'm able to select the hazard type.
![screen shot 2018-01-09 at 2 02 48 pm](https://user-images.githubusercontent.com/1164551/34745570-cd0ee7cc-f545-11e7-962a-7eafb06a7d3f.png)
![screen shot 2018-01-09 at 2 02 10 pm](https://user-images.githubusercontent.com/1164551/34745530-b43372fe-f545-11e7-961f-925d13d30457.png)

**Comment by allochi** [comment]
Fixed. Expected @v2.03
