### ISSUE TITLE
IDMC Backend - V2.01 production: Household size multiplier

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#238]
It would be much more user friendly to have the household size multiplier to default to "Lookup". currently the system is set to "Manual".
![screen shot 2018-01-09 at 10 10 33 pm](https://user-images.githubusercontent.com/1164551/34758050-1800331e-f58a-11e7-846c-4990d1a3f51e.png)

**Comment by allochi** [comment]
Fixed. Expected v2.03
