### ISSUE TITLE
IDMC V2.01 production: To move Estimate column between Country and Event

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#240]
Please can the column showing the Estimate for each Fact be moved between the Country and the Event in order to become immediately visible? This would help the quick Fact check after completing the entry.
thank you
![screenshot 89](https://user-images.githubusercontent.com/23187213/34769633-ace204de-f5fe-11e7-9cdb-73d345b07eac.png)

**Comment by allochi** [comment]
Done. Expected v2.03
