### ISSUE TITLE
IDMC V2.02 production: Issue: To add "Year" field in the search criteria (or make it possible to just type the year in the "Start Date" field)

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#241]
At the moment, it is not possible to just type the year in the search fields (event/fact/etc). Please can it be added? Either as a separate search field or make it possible to perform a search by year in the existing Start Date field (it doesn't work when I try to launch it). Thanks a lot!
![screenshot 90](https://user-images.githubusercontent.com/23187213/34774502-dc96b51a-f60f-11e7-927c-09c5c3bca6dd.png)

**Comment by allochi** [comment]
Added. Expected v2.03
