### ISSUE TITLE
IDMC V2.02 production: Issue: Search setting is lost when refreshing page

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#242]
Whenever I refresh a search page, the search selected settings are emptied, and I need to reset them again. It could be really useful to  be able to keep the search and be able to refresh the page in order to check if the changes made have been reflected (eg. modification of the name of an event, etc.)
Thank you!
![screenshot 91](https://user-images.githubusercontent.com/23187213/34780032-4548d5fe-f622-11e7-8fa9-e47418544070.png)

**Comment by allochi** [comment]
#247 Fixed
