### ISSUE TITLE
IDMC V2.02 production: Need: To expand the Comment field vertically in Event

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#244]
Please, this is truly needed: can the Comment field be expanded vertically in the Event page? It's an important field for everyone who didn't work on the disaster and would prevent scrolling up and down and missing crucial info while doing so.
Thanks a lot!
![screenshot 93](https://user-images.githubusercontent.com/23187213/34781644-aa24b16a-f626-11e7-9efd-edf20f521ca3.png)

**Comment by allochi** [comment]
Fixed. expected @2.03
