### ISSUE TITLE
IDMC Backend - V2.02 production: BUG: Events are not loading 

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#245]
As of 730am GVA time, Events are not loading
![screen shot 2018-01-10 at 10 30 56 pm](https://user-images.githubusercontent.com/1164551/34811521-1b57949a-f656-11e7-9c52-33f476d776e2.png)

**Comment by allochi** [comment]
This has been fixed. The cause of this error has been addressed also, and it's going to be pushed in the next update.
