### ISSUE TITLE
Production V2.02: Bug: Failed to delete fact

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#253]
- When I tried to delete a fact (not a quick fact), I received an error message stating that the database failed to delete the fact

**Comment by MartaLindstrom** [comment]
Message: "Failed to delete: function public.delete_fact_by_id(obj_id => unknown) does not exist"

**Comment by allochi** [comment]
Problem with the delete function. Fixed. Expected @v2.03
