### ISSUE TITLE
Production V2.04: Original source document can't be downloaded from the fact screen

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#266]
When viewing a fact: e.g. https://backend.idmcdb.org/facts/5779 in the MAIN tab, under association, there's a button to download the original document. When I click on it I'm led to a blank screen: https://backend.idmcdb.org/files/3fce9466-c13b-4df6-8c96-1f2e2ae60e11.pdf even thought the original source document is associated to the DOCUMENT. In order to see it, I have to go to the DOCUMENT: https://backend.idmcdb.org/documents/2729 and click on download document there: https://backend.idmcdb.org/upload/files/3fce9466-c13b-4df6-8c96-1f2e2ae60e11.pdf

**Comment by allochi** [comment]
Good catch, Fix in development, expected in the next update.
