### ISSUE TITLE
Production V.2.04 - Can't upload BBC document

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#267]
I tried using the link or also uploading a printed PDF for the document: https://backend.idmcdb.org/documents/2672 (link works) but the attached document is blank.

**Comment by allochi** [comment]
I check the page, it seems the video there causing the converter to crash, I'm sorry at the moment I don't have a solution for this problem, recommended workaround is to convert the page into PDF through Chrome.
Until I find a better software (there is one but it cost 5K, this is out of the budget for this task)
