### ISSUE TITLE
IDMC Backend - V2.04 production: BUG: End Date not showing

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#274]
After entering an end date for a fact and saving, it does not show up when the page is refreshed
![screen shot 2018-01-29 at 11 21 37 am](https://user-images.githubusercontent.com/1164551/35529717-c3b9e5d6-04e6-11e8-8e67-08c9d9acaf7b.png)
.

**Comment by allochi** [comment]
Fixed in the next update. Thanks for catching this.
