### ISSUE TITLE
IDMC Helix - v2.05 production: Cannot add dates in strata data

### ISSUE THREAD

**Issue by MiroStej** [idmc-labs/idmc-database-feedback#285]
The last line of dates is cut from view in the dates pop up window

**Comment by allochi** [comment]
is this fixed?

**Comment by MiroStej** [comment]
Yes, now it is fine

M

Miroslav Stejskal
Intern, Data Analyst
Data and Analysis Department
Internal Displacement Monitoring Centre (IDMC)
Norwegian Refugee Council
Rue de Varembé 3, 1202 Geneva, Switzerland
www.internal-displacement.org<http://www.internal-displacement.org/>

[cid:image003.png@01D38889.E2782CA0]
