### ISSUE TITLE
Bug: Not possible to conduct multiple confidence assessments

### ISSUE THREAD

**Issue by MartaLindstrom** [idmc-labs/idmc-database-feedback#292]
- Having completed the confidence assessment for the Myanmar stock master fact, I discovered that this information was copied over to the Myanmar R-Flow fact, R Stock fact, etcetera - as well as to the South Sudan master fact confidence assessments. When I made a change in the R-Flow fact, this change was also copied to the confidence assessment of the R Stock fact, and vice versa. So it was not in fact possible to conduct multiple confidence assessments. I am guessing that this must be due to a bug?

**Comment by allochi** [comment]
fixed
