### ISSUE TITLE
IDMC Helix - v2.16.10 production: Cannot clear masterfact association

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#338]
When click on "Clear", the masterfact association disappears however when page is reloaded the association is still there.
![screen shot 2019-02-21 at 1 59 02 pm](https://user-images.githubusercontent.com/1164551/53204685-16539180-35e1-11e9-8a0b-e7ae2f6f33e6.png)

**Comment by allochi** [comment]
Fixed and it will be in the next update v2.17.5
