### ISSUE TITLE
IDMC Helix - v2.17.1 production: Cannot see uploaded file

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#339]
With the change in the Document form, I cannot see the uploaded document. Previously there was a link, but when I click on the "Download File" button, I get an error message from this URL: https://upload/files/701ae37f-26b7-4a83-9cd3-2cd9f19bf4e6.pdf

![screen shot 2019-02-26 at 3 31 18 pm](https://user-images.githubusercontent.com/1164551/53454375-cc511e00-39db-11e9-8b19-7dd4089be540.png)

**Comment by allochi** [comment]
This has been fixed
