### ISSUE TITLE
IDMC Helix - v2.17.1 production: Cannot delete locations

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#340]
I can't delete locations... I right click on the location and click on the delete menu item, but nothing happens. Also notice that there's no line for the text field where you enter the location

![screen shot 2019-02-26 at 3 40 10 pm](https://user-images.githubusercontent.com/1164551/53454732-ff47e180-39dc-11e9-98d0-95abc6f8004e.png)

**Comment by allochi** [comment]
This has been fixed and it will be in the next update v2.17.5
