### ISSUE TITLE
IDMC Helix - v2.17.2 production: Bug - Masterfact created from Document

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#346]
When clicking on "Create new fact" from document, a masterfact is created instead of a fact. This is a big issue as we cannot create facts to attach to disaster events!

There's an error message that pops up when I try to create a new fact from the document:
![screen shot 2019-02-27 at 10 52 16 pm](https://user-images.githubusercontent.com/1164551/53546924-7915c300-3ae2-11e9-821f-e490113f825f.png)

**Comment by allochi** [comment]
Thanks for reporting this, it's fixed and will be pushed in a patch update today.
