### ISSUE TITLE
IDMC Helix - v2.17.8 production: Subfacts hyperlinks can't be copied & opened

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#349]
Hi Ali,

When I try to right-click and get the hyperlink of a subfact copied from the drop-down menu, it is not possiblle anymore. See the image captured. Please can you look into it? 
Thank you very much, 
Luisa

![CaptureCopy](https://user-images.githubusercontent.com/23187213/54434478-a5f6e680-472e-11e9-86b1-9946ab317936.PNG)

**Comment by allochi** [comment]
I fixed this, it will be in the next update.
