### ISSUE TITLE
Bug: Location field is adding [] 

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#35]
When I create a report the location field adds [] to my location. E.g. I enter Quebrada Honda and it is saved as [Quebrada Honda]. The problem is that [] keep being added every time I submit edits to the report. E.g. if I go back to add a comment and then submit it (without modifying the location) it  now gets saved as [[Quebrada Honda]].

**Comment by allochi** [comment]
Fixed
