### ISSUE TITLE
IDMC Helix - v2.17.8 production: Error signalled "UUID is missing"  

### ISSUE THREAD

**Issue by luisamg** [idmc-labs/idmc-database-feedback#350]
Hi Ali,

I just wished to let you know that since yesterday there is an error message appearing when we try to grab a PDF for the document page (see image). 

It says " UUID is missing - try to save and refresh the page before uploading". 

Afterwards, there is a Success! Saved green message, which means that the PDF is eventually grabbed.

Thought you still might want to know about it though.

Thank you,
Luisa

![CaptureUUID](https://user-images.githubusercontent.com/23187213/54435421-bad47980-4730-11e9-97ea-c5798732013f.PNG)

**Comment by allochi** [comment]
Could you please give me the document ID? thanks!

**Comment by allochi** [comment]
I pushed a fix for this, please try it out and if the issue persist, I will have to dig deeper into the problem.
