### ISSUE TITLE
IDMC Helix - v2.17.9 production: Events from 2019 are not showing in list

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#352]
Trying to search for events for 2019 and they do not show on list... an error message is presented. It seems that when searching for a particular country creates the error is the list of events.

This is a serious issue as I usually use the search function to see if events/figures I've come across have already been added to the database. 

![Screen Shot 2019-04-22 at 10 05 14 PM](https://user-images.githubusercontent.com/1164551/56555929-3ce36980-654b-11e9-8232-dd94fbdc064a.png)

**Comment by allochi** [comment]
Hi Vincent, I couldn't replicate the error, I tried the same country and year, could I ask you to click on the reset button and refill the form with your criteria and see if you still get the error.

**Comment by ghost** [comment]
Hey Ali,

It seems to be working again. Not sure what happened.

Vincent
