### ISSUE TITLE
Household number does not automatically calculate from AHA

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#45]
The household figure does not generate after entering a number. 
![screen shot 2016-11-22 at 11 23 28 am](https://cloud.githubusercontent.com/assets/1164551/20538489/52db737e-b0a6-11e6-8900-9a0e99a68d64.png)

I already inputted the average household size in the initial report screen... I can't add the household size in the report main page.
![screen shot 2016-11-22 at 11 25 52 am](https://cloud.githubusercontent.com/assets/1164551/20538517/762bb5f0-b0a6-11e6-96fb-0e9d1022f38a.png)

This affects the Event page as it does not show the estimate figure
![screen shot 2016-11-22 at 11 26 35 am](https://cloud.githubusercontent.com/assets/1164551/20538553/990c65d8-b0a6-11e6-8bad-d84186bb9c30.png)

**Comment by allochi** [comment]
Thanks for reporting this, I'm sorry about this, I found out that I misplaced a bracket in the form, which led to this situation. You can send me the list of affected reports and I can update their household directly from the database.

This should be fixed now.

**Comment by ghost** [comment]
Hi Ali,

I can update the reports myself. It wasn't many.

Cheers,
Vincent

**Comment by ghost** [comment]
Hi again Ali.... 

I just tried to update the figure but the auto generated AHA figure doesn't work. I think I need to recreated the reports again. So maybe it's better you update it directly in the database. Here are the report IDs:

R2016-THA-000018
R2016-THA-000019
R2016-THA-000020
R2016-THA-000021
R2016-THA-000022
R2016-THA-000023
R2016-THA-000024

Thanks,
Vincent
