### ISSUE TITLE
Location and commas

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#48]
The locations save individually after a comma in Reports but it is all grouped together in Events. It would be great if locations in Events would be saved individually when using a comma after each place.

See: E2016-THA-000011

![screen shot 2016-11-23 at 3 19 51 pm](https://cloud.githubusercontent.com/assets/1164551/20581832/545aedd4-b190-11e6-8b0e-6475d36138b1.png)

**Comment by IvanaHajz** [comment]
Hmmm weird, I dont have this problem. Even in events, all the places are saved individually.

**Comment by ghost** [comment]
i can't paste a long string of locations using commas where the system would then separate out each location.

For example: Dak Lak, Ha Tinh, Quang Binh, Quang Tri, Thua Thien Hue, Quang Ngai, Binh Dinh, Phu Yen, Khanh Hoa, Ninh Thuan, Binh Thuan, Kon Tum, Gia Lai,
