### ISSUE TITLE
URGENT: Can't upload documents. 

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#59]
I am getting the following message when I tried to create a document: "Something went wrong storing the document: ERROR #23505 duplicate key value violates unique constraint "documents_serial_no_key" (addr="[::1]:5432")"

I have tried to upload a PDF and to use a link, and I have tried with different documents, I also tried Safari and Chrome. 

[AAAscreenshotproblemdocument.pdf](https://github.com/idmc-labs/idmc-database-feedback/files/691485/AAAscreenshotproblemdocument.pdf)

**Comment by ghost** [comment]
Yes... same with me! Same error 
![screen shot 2017-01-08 at 2 49 06 pm](https://cloud.githubusercontent.com/assets/1164551/21754297/4410bc88-d5b2-11e6-8fd7-c6182873882b.png)

**Comment by allochi** [comment]
I'm working on this issue.

**Comment by allochi** [comment]
This has been fixed, the only reason I can find that caused this was that the publication date was changed after a document was saved, so the serial no was created for 2016, but the publication date was changed to be 2017.

Anyway, long story short it should work now.
