### ISSUE TITLE
New DB: Double facts

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#61]
It seems that the new database is doubling up on facts. 

In the old database under "Reports", there are a total of 1889 entries (as of 3 Feb)
In the new database under "Facts", there is 3192 entries...

For example, this Philippines document (http://139.162.221.150:3300/app/documents/edit/1060) shows double facts. It seems to be because I have entered both a Stock and New displacement figure in Report (http://139.162.221.150:5900/app/reports/edit/1281) that references the same document. 

![screen shot 2017-02-03 at 3 59 08 pm](https://cloud.githubusercontent.com/assets/1164551/22613045/c2b74148-ea29-11e6-9c74-739678bfeebe.png)

Also the Stock figure value in Facts (http://139.162.221.150:3300/app/facts/edit/1505) does not pull in the date from the old database to populate the Start and End Date. 

![screen shot 2017-02-03 at 4 08 19 pm](https://cloud.githubusercontent.com/assets/1164551/22613178/04581bda-ea2b-11e6-8af3-99f86ca03a33.png)

Also http://139.162.221.150:3300/app/facts/edit/1505 is referencing the wrong Master Fact (i.e. it is not related to Hurricane Matthew)

![screen shot 2017-02-03 at 4 09 25 pm](https://cloud.githubusercontent.com/assets/1164551/22613210/44a7bd3a-ea2b-11e6-996c-1fcb61a1bb2d.png)

**Comment by allochi** [comment]
Hi Vincent, I'm sorry that my reply come late, it's normal to have fact increase as reports have been broken down to facts, and we used to have reports that contain multiple facts, same goes for the events.

I hope the other issues are now resolved with the new update.

Please if you still encounter any errors with association we can resolve them together by going to through the records history and backup.
