### ISSUE TITLE
New DB: Document Upload Error

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#62]
I received this error when I tried to upload a document.

![screen shot 2017-02-04 at 9 54 22 pm](https://cloud.githubusercontent.com/assets/1164551/22624038/969468ba-eb24-11e6-9408-0ddbb4f8832d.png)

**Comment by andreslizcano** [comment]
+1

**Comment by andreslizcano** [comment]
And then I got the following error as well: Something went wrong storing the document: ERROR #23502 null value in column "original_filename" violates not-null constraint (addr="[::1]:5432")
