### ISSUE TITLE
New DB: General Issues

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#63]
- Dates: you can enter 6 digits in year (probably should limit this to 4 digits)
- Can't select Groups or Themes in Facts... no drop down options
- How do you add multiple sub facts to an event? Looks like this can be done according to Leonardo's "Data Collection Guidelines".
- Would be great once adding a Master Fact is selected to move to the next screen where details can be entered... currently once you save the Master Fact, you stay on the same page. This means that I have to go back to the Fact list, find the fact I just entered in the search box, click on it, and then add details... in terms of usability/user experience, this is not ideal.

**Comment by allochi** [comment]
Most of the issues have been taken care of, except for the year field. Thanks!

**Comment by allochi** [comment]
Year also fixed.
