### ISSUE TITLE
Can't open document from fact

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#66]
When I'm looking at a fact and click to open the associated document, it doesn’t open - even though the document is uploaded properly (I checked by searching the document separately and it works).

**Comment by allochi** [comment]
Could you give an example, I tried it an it does open, this could be a specific fact/document. Let's see how it act after the final migration.

**Comment by andreslizcano** [comment]
Yes, this is fixed now.
