### ISSUE TITLE
NEW DB: Fact Issues

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#71]
- it would be good to highlight when we're in a Master Fact or a normal fact. It's only apparent with the tabs, but it might be good to have it stated in the title

- The "Submit" button doesn't work on the Facts. I've attached a subfact to a master fact but it does not show up in the list

![screen shot 2017-02-06 at 4 41 13 pm](https://cloud.githubusercontent.com/assets/1164551/22672853/5451aa04-ec8b-11e6-99a0-1d85a5ca72f8.png)

- Both fact types are listed under Facts. I've created a Master and a subfact but it is difficult to tell which is which... As I've worked on Indonesia and Philippines, there are many facts that are associated with events so this will be problematic as it requires a lot of time to understand which facts are master and sub, especially if I'm dealing with 20-30 data points for one event and one type (i.e. stock).
![screen shot 2017-02-06 at 4 44 41 pm](https://cloud.githubusercontent.com/assets/1164551/22672897/9a7fa558-ec8b-11e6-8e14-e2617714e1d7.png)

**Comment by allochi** [comment]
Thanks for the feedback, they have been adopted into the system.
