### ISSUE TITLE
cannot submit document

### ISSUE THREAD

**Issue by milanoleonardo** [idmc-labs/idmc-database-feedback#75]
I get the following error:

There was an error with your request
ERROR #23502 null value in column "original_filename" violates not-null constraint (addr="[::1]:5432")

**Comment by andreslizcano** [comment]
Besides the issue Leonardo mentions, I think it is problematic that we can't upload files, since some of the information is based on emails I received. Is there any way of dealing with that?

**Comment by allochi** [comment]
This should be solved now, the document no more require a URL when created and a file can be uploaded after the document has been created.
