### ISSUE TITLE
New DB: Document issues

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#80]
- I created this document: http://139.162.221.150:3300/app/documents/edit/1595. When I submit/save the document the associated meta data (i.e. country, publisher, source, displacement type) does not save.

![screen shot 2017-02-13 at 11 47 53 am](https://cloud.githubusercontent.com/assets/1164551/22900181/49861a18-f1e2-11e6-9a2e-72efd818fcf1.png)

- It would be great to be able once a fact is added to the document to be able to access the document again via a tab or something... for the moment, once the fact is added I have to go back to the document list, search for my document and then find my fact.

- Comma delimited list of names/places does not create individual entries... an issue from old DB as well. I usually copy/paste together a list of locations (ex. Nuristan, Badakhshan, Kunar, Parwan, Daykundi, Bamyan) and then paste it into the locations sections. The system does not create separate entries from this list. If I had to manually type each one, it would not be very user friendly or efficient.

![screen shot 2017-02-13 at 11 45 40 am](https://cloud.githubusercontent.com/assets/1164551/22900261/958e61ea-f1e2-11e6-9e16-1e25b9f81709.png)

- I created this fact through Documents: http://139.162.221.150:3300/app/facts/edit/3258. However none of the Figure or Location information is there when I open this fact through the Facts menu. The information is still there if I view it through Documents. 

**The screenshot of the fact using the Facts menu link** 
![screen shot 2017-02-13 at 11 56 31 am](https://cloud.githubusercontent.com/assets/1164551/22900569/9f31f7ce-f1e3-11e6-9c4d-9fb9c34416b6.png)

**The screenshot of the fact using the Documents menu link**
![screen shot 2017-02-13 at 11 59 16 am](https://cloud.githubusercontent.com/assets/1164551/22900675/00bbdb54-f1e4-11e6-8182-129664866396.png)

**Comment by allochi** [comment]
Hi, The forms have been updated, I checked these issues and they seems to be resolved. Please check them out and if any reoccur, Please open the ticket again.

Thanks for your feedback.
