### ISSUE TITLE
Possible problem with migration of documents associated with several reports

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#81]
For Paraguay, there are reports that aren’t linked to any documents/ reports. The same happens for the master fact of the Hurricane Otto Stock Figure for Panama (F2016-PAN-000005) there is no associated subject or document. I think it might be an issue with the migration of documents that were associated with two or more reports. If this is the case, we might have a lot of documents missing.

**Comment by allochi** [comment]
Hi Andres, Could we please go through this together and check which documents you think are missing. Thanks.
