### ISSUE TITLE
Can't modify qualifier and unit in the data tab of the fact editing window

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#84]

**Comment by andreslizcano** [comment]
When I create a fact I cannot modify qualifier and unit. Once the fact is created I can. I thought it wouldn't save changes I made (including in the dates), but I think it is just taking a while/ I just need to reload a few times for them to show up.

**Comment by andreslizcano** [comment]
Sorry for the confusion: I don't understand when the fact sheet is saving my changes and when it isn't doing it. But I do know that in many cases it is not saving dates, displacement estimate, qualifier, unit, and association to a master fact.

**Comment by allochi** [comment]
The fact form has been updated, the new update should address this issue. Please reopen the ticket if the bug reoccur.
