### ISSUE TITLE
NEW DB: Error for dates

### ISSUE THREAD

**Issue by ghost** [idmc-labs/idmc-database-feedback#86]
The dates are correct but why do I get this error?
http://139.162.221.150:3300/app/facts/edit/2507

![screen shot 2017-02-17 at 11 21 23 am](https://cloud.githubusercontent.com/assets/1164551/23079824/5da12398-f503-11e6-808d-6a980100dda5.png)

**Comment by allochi** [comment]
I checked this bug with the new update, and it seems to be fixed, Please open the ticket again if it reoccur. Thanks!
