### ISSUE TITLE
Documents have empty fields

### ISSUE THREAD

**Issue by andreslizcano** [idmc-labs/idmc-database-feedback#87]
When uploading/ editing a document: Displacement Types, Countries, Sources & Publishers show up empty and remain empty after editing and reloading. 

I'm having this issue with the following document: http://139.162.221.150:3300/app/documents/edit/1497

**Comment by allochi** [comment]
The document form has been updated to address this issue, I checked the provided link and it seems to work fine now. Please reopen the ticket if the bug reoccur.
